# Generated by Django 6.0.5 on 2026-05-12 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CommandLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("target_client_id", models.CharField(max_length=128)),
                ("command", models.CharField(max_length=32)),
                ("issued_at", models.DateTimeField(auto_now_add=True)),
                ("status", models.CharField(default="queued", max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("device_type", models.CharField(max_length=64)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ModbusServerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("host", models.CharField(max_length=255)),
                ("port", models.PositiveIntegerField()),
                ("unit_id", models.PositiveIntegerField(default=1)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="devices.device"
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("host", "port", "unit_id"),
                        name="uq_modbus_endpoint_unit",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MqttClientProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_id", models.CharField(max_length=128, unique=True)),
                ("asset_id", models.CharField(max_length=64)),
                ("symbol", models.CharField(max_length=16)),
                ("telemetry_topic", models.CharField(max_length=255)),
                ("command_topic", models.CharField(max_length=255)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="devices.device"
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("telemetry_topic",),
                        name="uq_mqtt_profile_telemetry_topic",
                    ),
                    models.UniqueConstraint(
                        fields=("command_topic",), name="uq_mqtt_profile_command_topic"
                    ),
                ],
            },
        ),
    ]
