# Generated by Django 6.0.5 on 2026-05-14 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="modbusserverprofile",
            name="last_seen_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="modbusserverprofile",
            name="runtime_status",
            field=models.CharField(default="unknown", max_length=16),
        ),
        migrations.AddField(
            model_name="mqttclientprofile",
            name="last_seen_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mqttclientprofile",
            name="runtime_status",
            field=models.CharField(default="unknown", max_length=16),
        ),
    ]
